### ISSUE TITLE
静态编译CUPS

### ISSUE THREAD

**Issue by HsingPeng** [openthos/printer-analysis#17]
由于bionic编译cups遇到困难，先使用静态编译CUPS到android x86中，测试cups运行情况。

**Comment by HsingPeng** [comment]
发现一篇文章里说编译包含动态链接库程序可运行在android。

地址： 《linux程序移植到android上》 http://thedevilking.blog.51cto.com/8144260/1364547 

虽然文中编译的是arm平台的程序，但是x86平台同理。按文章说明应该能够成功使用。
这样我们就可以：
1.  编译包含动态链接库的程序，重复利用库，减少程序体积。
2.  有可能成功使用只有二进制驱动的奔图打印机等等。

你们先看看，具体还得再分析。

**Comment by chyyuu** [comment]
很不错！
也请注意阶段的目标是否已经完成．
