### ISSUE TITLE
HeXingPeng :: printer: Plan 2016503 -- 20160531

### ISSUE THREAD

**Issue by chyyuu** [openthos/printer-analysis#19]
何兴鹏
5月3日 ~ 5月8日         整合CUPS进android
5月9日 ~ 5月15日                    编写CUPS交流接口 中 打印
5月16日 ~ 5月22日                  与北大同学沟通，编写通知栏接口
5月23日 ~ 5月29日                完善程序

潜在困难：
 cups读写USB的权限问题，安卓不允应用直接读写usb设备。之前没有用cups时，通过接入android usb框架，在java层实现读写。而cups使用libusb库直接读写usb设备文件。安卓中有个usb用户组能直接读写，我在尝试修改程序权限，想让程序加入usb用户组，还在寻找方法。

网络功能不知道CUPS移植后能不能用

**Comment by HsingPeng** [comment]
**进展：**
已完成/完成80%
修改frameworks/base/data/etc/platform.xml源码，加入自定义USB用户组权限。
并且通过使用系统签名，使得程序成功加入USB用户组，获得usb读写的权限。已测试。
测试杨茂静态编译的CUPS，可以添加删除打印机。
修改cupsd.conf配置文件，解决CUPS控制权限问题。

**偏差：**
还差把之前编译的gs等加入，实现打印。

**问题：**
无

**帮助：**
无

**下周：**
这周末完成本周工作，保证下周工作正常进行。

**Comment by HsingPeng** [comment]
本周小组主要完成了CUPS的移植，但是还没完全测试。正在整合驱动，进行测试。该部分工作由杨茂、何兴鹏完成。
其他成员本周没有指定具体任务，他们在为下面的工作做准备，从下周开始执行。
按计划这周要完成CUPS的整合，目前还未完成整合。所以在本周末我会完成工作。

下周按计划进行。若有变，我会及时通知。

2016年5月6日18:54:13

**Comment by HsingPeng** [comment]
# 进展：

已完成/完成80%
整个cups已经能够在openthos中成功部署，并且完成打印机管理功能完好。
打印测试页成功。

# 偏差：

但是打印pdf功能有问题，因为之前调研时忘记测试pdf打印，所以缺少pdf转换功能。已加入杨茂下周任务。

# 问题：

缺少pdf打印功能

# 帮助：

无

# 下周：

计划基本正常，但是得抓紧时间。

2016-5-8 23:00:20

**Comment by HsingPeng** [comment]
进展：
本周由于课堂事情较多，影响了项目进度。
我考量了原有的命令行交互模式，决定完善交互代码，现在还构架CUPS交流的框架。
等我的框架代码写完，才能进入具体的操作编写。所以陶琛嵘前面的CUPS交流接口收集完毕之后，帮助杨茂完成本周的编译工作。

偏差：
差两天的工作量。

问题：
无

帮助：
无

下周：
这周末完成本周工作，保证下周工作正常进行。

2016-5-13 19:43:56

**Comment by HsingPeng** [comment]
# 进展：

本周进展较慢，未能完成周计划。

# 偏差：

驱动部分移植遇到困难，pdf转换器未移植。
由于CUPS交流的框架构建延误，导致CUPS交流代码未能及时编写。

# 问题：

移植有困难。

# 帮助：

无

# 下周：

完成上周任务，赶上进度。

2016-5-16 13:07:07

**Comment by HsingPeng** [comment]
# 本周任务调整：
1. 本周帮助杨茂完成驱动编译。
2. 完善CUPS交流框架。
3. 通知栏部分已在沟通。

**Comment by HsingPeng** [comment]
# 进展：

本周进展顺利。
由于之前静态编译gutenprint驱动出现了很多问题，于是尝试使用动态编译。
经过几天的努力，已经成功完成动态编译程序在android_x86下的部署和运行。
编译的软件包有：
cups-2.1.2
cups-filters-1.8.2
ghostscript-9.18
foo2zjs

目前能够成功添加删除打印机，打印测试页及pdf文档等。

其他的软件包会陆续加入，比如gutenprint以及奔图打印机驱动等。

目前整体大小占用有87M左右，这是解压部署后的大小，个人认为大小较为理想。压缩后的大小为37M。

# 偏差：

由于制作通知栏的同学需要考试，暂时不能制作打印机通知栏，需要我们自己制作。考量时间因素，我们决定把通知栏制作放在后续进行。本月优先完成程序必要功能。

# 问题：

无

# 帮助：

无

# 下周：

下周将和陶琛嵘编写CUPS接口，以及完善程序的功能。
打印任务管理部分，待郑华利，卢晓蓉的界面制作完成再实现。

2016-5-22 12:29:52

**Comment by HsingPeng** [comment]
# 进展：

## 1 交流接口部分

截止到本周，CUPS交流接口完成情况如下：

A CUPS管理
- [X]  A1检测cups是否运行
- [X] A2 启动cups
- [ ] A3 关闭cups

B 打印机管理
- [X] B1 查询可用打印机驱动
- [X] B2 添加打印机
- [X] B3 查询已添加打印机
- [X] B4 删除打印机
- [ ] B5 修改打印机配置
- [X] B6 查询打印机状态和配置
- [ ] B7 设置默认打印机
- [X] B8 查询可添加打印机
- [ ] B9 查询打印机设置

C 打印任务管理
- [X] C1 打印
- [ ] C2 查询打印任务
- [ ] C3 取消打印任务

D 网络打印机管理

暂时搁置

## 2 总体

从整体上来说，程序主要功能实现情况如下：
- [X] 打印机添加，删除
- [x] 打印
- [ ] 打印机配置  （正在完成）
- [ ] 打印任务管理 （正在完成）
- [ ] 网络打印机
- [ ] 通知栏状态

打印机支持情况如下：

| 已支持 | 打印机 | 驱动 |
| --- | --- | --- |
| √ | 部分HP激光打印机 | foo2zjs |
| √ | 部分Epson喷墨打印机 | 官方旧版开源驱动 |
| √ | 大部分奔图打印机 | 官方闭源驱动 |
|  | 部分HP喷墨打印机 | hpcups |
|  | 部分Epson打印机 | gutenprint |

未打勾的是准备加入的驱动。对于Epson打印机，虽然官方的新版驱动能够驱动几乎所有的该品牌打印机，但是Epson新版驱动是以daemon程序的形式存在，而不是作为一个cups过滤器。所以先使用旧版驱动，待实验新版驱动如何和cups结合再尝试加入。

目前只测试了奔图驱动、foo2zjs中一部分、Epson官方旧版驱动、还有一些过滤器有待测试。
暂时来说，测试驱动不需要接入该品牌打印机，只需要检测cups过滤器运行成功即可。这种方法只是没有检测最后的数据输出情况，但是前面的流程都可以测试。

# 偏差：

打印机配置和打印任务管理未能如期完成，还在完成中。

# 问题：

还有很多细节有待完善。比如：双面打印，程序界面友好提示，自动选择打印机驱动。

# 帮助：

无

# 下周：

完成打印机配置和打印任务管理。

**Comment by HsingPeng** [comment]
# 进展：

打印机配置和打印任务管理的逻辑及界面部分制作完毕，打印接口有待完成。

# 偏差：

临近期末，完成较慢。

# 问题：

无

# 帮助：

无

# 下周：

完成打印通知栏。

**Comment by HsingPeng** [comment]
进展：

通知栏部分制作遇到问题，未完成。

偏差：

未能按时完成计划任务。

问题：

安卓原生通知栏不支持通知动态布局，必须使用布局文件制定布局。但是打印任务数量是动态改变的，所以不能正确布局。也可能是我理解的还不够，导致无法实现。

帮助：

无

下周：

由于时间有限，而且cups打印交流接口部分还没完成，所以我暂时不做通知栏了。我测试和完善接口，确保在这个星期日完成打印机配置和任务管理功能。先完成已在制作的功能，之后再完成通知栏。

**Comment by HsingPeng** [comment]
# 进展：

已完成打印机配置修改功能，以及打印任务管理。但是还有一些bug有待修复。

# 偏差：

与本周计划基本一致。

# 问题：

有两个明显问题：
1. 打印任务的状态有时不能正确显示。
2. 打印任务从暂停状态恢复时，有时命令是无效的。目前认为这很可能是cups部分的问题，命令成功发送，但是没有生效。

# 帮助：

无

# 下周：

由于主要时间在完成课程大作业和期末考试，下周只计划修复已知的两个问题。
