### ISSUE TITLE
TaoShenRong :: printer: Plan 2016503 -- 20160531

### ISSUE THREAD

**Issue by chyyuu** [openthos/printer-analysis#20]
陶琛嵘
5月3日 ~ 5月8日     学习CUPS交流接口编写
5月9日 ~ 5月15日           编写CUPS交流接口 中 打印机管理
5月16日 ~ 5月22日       编写CUPS交流接口 中 打印任务管理
5月23日 ~ 5月29日       编写CUPS交流接口 中 网络打印机管理

**Comment by taocr** [comment]
进展：
已完成打印机调研工作，上传打印机支持情况调研报告
学习CUPS交流接口编写

偏差：
由于CUPS交流接口方面找到的参考资料是使用Java编写的，而我对Java并不熟悉，所以看得比较困难，不过正在加快进度，争取尽快进入编写工作。

问题：

帮助：

下周：
完成CUPS交流接口的学习工作，开始计划中打印机管理方面的交流接口编写。

**Comment by HsingPeng** [comment]
调研报告完成较慢。

**Comment by HsingPeng** [comment]
# 下周任务：

安装android studio 之后到我实验室，研究编写接口。

**Comment by taocr** [comment]
进展：
CUPS交流接口如何实现调研大致完成，参考了别的项目调研具体各项功能如何完成，并对一些缺少的功能进行实验调查如何完成。
由于网络打印机的功能方面不清楚是否能够正常运行，且上次会议中决定搁置对网络打印机的支持情况，先完成对usb方面的两款打印机的支持，因此对网络打印机管理方面的功能暂未调查。

完成把移植文件内的busybox文件全部换成软连接的脚本编写

偏差：
目前仍未进入打印机接口的具体编写工作，不过下星期会加快对具体接口的编写，赶上进度

问题：
无

帮助：
无

下周：
开始进入打印机交流接口的编写工作

**Comment by HsingPeng** [comment]
本周我耽误了些时间，你先帮助杨茂编译。

**Comment by HsingPeng** [comment]
# 本周任务调整

完成CUPS的交流命令编写。有如下命令：

### A CUPS管理

A1 检测cups是否运行
A2 启动cups
A3 关闭cups

### B 打印机管理

B1 查询可用打印机驱动
B2 添加打印机
B3 查询已添加打印机
B4 删除打印机
B5 修改打印机配置
B6 查询打印机状态和配置
B7 设置默认打印机
B8 查询可添加打印机

### C 打印任务管理

C1 打印
C2 查询打印任务
C3 取消打印任务

交流框架已经搭好，只需要处理输出的数据，格式化为需要的形式。
请及时前来讨论。

**Comment by taocr** [comment]
进展：
开始编写CUPS交流接口，还未完成

偏差：
完成速度缓慢，需要加快速度

问题：
无

帮助：
无

下周：
继续完成交流接口的编写

**Comment by HsingPeng** [comment]
# 本周任务：

我们将在本周内完成CUPS接口的编写。

请上报你目前的编写情况，每个人完成剩下的一部分。

**Comment by taocr** [comment]
进展：
完成部分CUPS接口的编写，并进行了测试

偏差：
无

问题：
无

帮助：
无

下周：
继续完成剩下的交流接口的编写工作并对运行结果进行测试

**Comment by HsingPeng** [comment]
# 下周任务

完成以下交流接口：

## B 打印机管理
- [ ] B5 修改打印机高级配置                         UpdatePrinterCupsOptionsTask
- [ ] B9 查询打印机高级设置                    QueryPrinterCupsOptonsTask
- [ ] B10 查询打印机设置                    QueryPrinterOptonsTask
- [ ] B11 修改打印机设置                     UpdatePrinterOptonsTask

## C 打印任务管理
- [ ] C2 查询打印任务                    JobQueryTask
- [ ] C3 取消打印任务                    JobCancelTask
- [ ] C4 暂停打印任务                    JobPauseTask
- [ ] C5 恢复打印任务                    JobResumeTask
- [ ] C6 取消所有打印任务          JobCancelAllTask
- [ ] C7 暂停所有打印任务          JobPauseAllTask
- [ ] C8 恢复所有打印任务          JobResumeAllTask

**Comment by taocr** [comment]
进展：
目前完成了B部分的交流接口的编写，C部分正在完成。
还没有进行测试，在完成所有的接口后进行测试。

偏差：
无

问题：
无

帮助：
无

下周：
完成交流接口的编写并进行测试

**Comment by HsingPeng** [comment]
我也加入接口编写，以及完善程序。在这周日结束前，完成打印配置和任务管理功能。

**Comment by taocr** [comment]
进展：
目前已基本完成CUPS交流接口的编写；
配合何兴鹏进行交流接口的测试工作，已经完成大部分的测试工作。

偏差：
无

问题：
测试中出现了某些情况下，打印任务的状态显示unkown的状态；
在单个任务的暂停以及恢复的工作中存在有时点击后无效的情况。

帮助：
无

下周：
完善出现的两个问题
