### ISSUE TITLE
YangMao :: printer: Plan 2016503 -- 20160531

### ISSUE THREAD

**Issue by chyyuu** [openthos/printer-analysis#21]
杨茂
5月3日 ~ 5月8日     完成CUPS编译运行（若有困难不能解决先拿出一个可用方案）
5月9日 ~ 5月15日            移植gutenprint驱动（若能用动态链接编译最好）
5月16日 ~ 5月22日       测试CUPS中的网络打印机功能
5月23日 ~ 5月29日       尝试移植奔图打印机驱动

潜在困难：
cups还没编译成功

**Comment by YangMao111** [comment]
# 本周工作：

编译参数：

```
./configure CFLAGS=-static --enable-static LDFLAGS=-static --disable-shared --prefix=安装目录
```

编译出错，修改Makedefs

```
LDFLAGS         =       -L../cgi-bin -L../cups -L../filter -L../ppdc \
                        -L../scheduler  \
                        -static  -fPIE -pie $(OPTIM)
```

删除  -fPIE -pie

```
LDFLAGS         =       -L../cgi-bin -L../cups -L../filter -L../ppdc \
                        -L../scheduler  \
                        -static $(OPTIM)
```

完成静态编译cups，交付何兴鹏。

# 下周工作：

编译移植foomatic-filter
编译移植gutenprint

**Comment by HsingPeng** [comment]
cups里面很多组件使用shell脚本编写，我正在测试是否能正常运行。

**Comment by YangMao111** [comment]
杨茂：
进展：顺利
偏差：无
问题：无
帮助：无
下周：按月计划进行

**Comment by HsingPeng** [comment]
# 本周任务调整通知：

由于现在CUPS打印系统部分移植成功，但是打印pdf文档出现问题。
原因是缺少pdftops过滤器，该转换器不在CUPS项目内，而是在Poppler项目中。
所以有以下几种方案：
1. 移植poppler或者xpdf（两者都有pdftops） 但是我移植失败了，缺库
2.移植cups2.1.2和cups-filter(该项目有自己的pdf转换器) 也是缺库

## 任务调整如下：
1. 把移植文件内的busybox文件全部换成软连接 （写脚本，详谈）
2. 检查可执行文件是否有链接错误
3. 编译上述pdf转换器，二选一，最好花几个小时，都试试。
4. 编译gutenprint驱动

## 注意：

请使用centos6 x86 系统移植，ubuntu中移植的有问题。（我这有镜像）
前期已经积累了大量的移植经验，现在移植应该轻松多了。
移植遇到问题的时候，及时到我实验室讨论。

**Comment by YangMao111** [comment]
杨茂：
进展：移植gutenprint驱动不太顺利
偏差：出现链接错误，正在解决
问题：无
帮助：无
下周：按月计划进行

**Comment by HsingPeng** [comment]
# 上周总结

## 进展

上周布置了4个任务。
其中 任务1 和 任务2 已交由陶琛嵘完成。
驱动移植和pdf转换器移植任务还未完成。

## 偏差

与计划的相差较大，gutenprint驱动移植遇到困难。pdf转换器还未来得及移植。

# 本周任务调整

由于暂时可以搁置网络功能，所以本周继续完成移植工作。
本周我会尽可能的帮助解决问题。

**Comment by YangMao111** [comment]
杨茂：
进展：静态编译问题未解决，尝试采用动态编译方式，编写脚本复制程序所需链接库，进展比较顺利
偏差：无
问题：无
帮助：无
下周：按月计划进行

**Comment by HsingPeng** [comment]
# 本周任务

由于动态编译的移植环境在我电脑上，我会顺便加入奔图打印机等驱动。

本周你加入CUPS接口编写，我们将于本周完成所有的接口编写。

**Comment by YangMao111** [comment]
杨茂：
进展：完成脚本编写，成功复制动态库
偏差：无
问题：无
帮助：无
下周：参与接口编写

**Comment by HsingPeng** [comment]
# 下周任务

在我们移植的cups中测试网络打印功能是否可用。

具体做法是，找出网络打印的命令，然后测试。比如：添加删除网络打印机等。

确定可用之后，记录命令以及操作步骤。
尽早完成，以便指定下一步计划。
