### ISSUE TITLE
ZhenHuaLi :: printer: Plan 2016503 -- 20160531

### ISSUE THREAD

**Issue by chyyuu** [openthos/printer-analysis#22]
郑华利 卢晓荣
5月9日 ~ 5月15日        编写打印任务管理页面
5月16日 ~ 5月22日       测试打印、打印机管理及编写程序操作交互提示
5月23日 ~ 5月29日       完善与测试

**Comment by HsingPeng** [comment]
郑华利 卢晓荣 两位同学主要以学习的方式加入项目，所以要求不紧迫。分配的是一些初级任务，但是也要求认真完成。

加油！

**Comment by zhlgithub** [comment]
安装android-studio软件，学习java视频的类集框架，开始进入安卓的学习。

**Comment by lxr0912** [comment]
看页面制作的相关视频，为后面的工作做准备。

**Comment by HsingPeng** [comment]
# 1 上周总结

上周我分享android开发的一些入门知识，希望你们对android软件开发有初步的了解。

# 2 本周任务

本周要求你们做出**打印任务管理界面**，如下图所示：

![image](https://github.com/openthos/printer-analysis/raw/master/APP/raw/20160516115812.png)

## 2.1 要求

按钮能够点击，点击后的功能不用实现。
表格数据是动态变化的。可自行写几条模拟数据，如图所示。

## 2.2 制作方法

通过观看android视频以及在网上搜索资料完成。

在android中，制作表格没有现成的控件，但是有很多方式做出来。
常用的控件有TableLayout，ListView，GridView等。

这里推荐使用ListView制作。

由于之前推荐的视频没有给出listview的教程，这里贴出一个有listview的视频教程，可参考学习。
http://study.163.com/course/courseMain.htm?courseId=877054

## 2.3 提示

整个页面是一个Activtiy，暂停所有等按钮写在activity的layout布局里，中间的数据部分是Listview。

所以需要先制作好activity后再制作listview。

也就是，先不用想着做listview，先做一个activity。

**Comment by zhlgithub** [comment]
郑华利：
进展：目前为止，只能实现一个简单的activity界面。
偏差：无
问题：关于listview和适配器方面的知识还在看，目前为止还在看视频和查资料阶段。
帮助：无
下周：按月计划进行

**Comment by HsingPeng** [comment]
第十二章-经典的ListView http://wiki.jikexueyuan.com/project/twenty-four-Scriptures/list-view.html

**Comment by lxr0912** [comment]
卢晓荣：
进展：目前只能制作简单的界面
偏差：无
问题：适配器和listview不熟悉，所以功能实现还有问题
帮助：无
下周：按月计划进行

**Comment by HsingPeng** [comment]
# 本周任务：

请先运行教程里的代码，然后看懂。
有疑惑的地方请直接问我。
再根据教程里的例子，写出符合要求的listview。
最迟于周三完成编写。
周三后再完善activity的功能。

**提示：**不要纠结在界面美化等细节上，优先完成功能。

**Comment by lxr0912** [comment]
卢晓荣：
进展：界面功能基本可以实现，有些细节部分还有待完善。
偏差：无
问题：监听器和标题部分还存在问题
帮助：无
下周：按月计划进行

**Comment by zhlgithub** [comment]
郑华利：
进展：界面功能基本实现，界面仍然不够美观，需做调整。
偏差：无
问题：标题和监听器部分存在问题。
帮助：无
下周：按月计划进行
