### ISSUE TITLE
交叉编译移植ghostscript和foo2zjs到android

### ISSUE THREAD

**Issue by HsingPeng** [openthos/printer-analysis#4]
参考
- [嵌入式打印机系统移植支持HP LaserJet 1020 plus 激光打印机和HP DeskJet 1010喷墨打印机](http://blog.csdn.net/xiaohuangzhilin/article/details/50134095)
- [Android遇上打印机](http://blog.csdn.net/kangear/article/details/18141741)

实验室已购置hp p1108打印机，经过测试，在桌面linux上通过ghostscript和foo2zjs可以成功驱动该打印机。
参考上述博文，移植两个包到android中，对于android使用x86虚拟机还是arm机器不限制。

目标：学会交叉编译，成功移植并在android中通过命令行可以实现打印。

**Comment by HsingPeng** [comment]
编译android_x86平台的程序直接使用GCC编译，参考

>  [为Android-x86编译tcpdump工具](http://blog.csdn.net/yang1982_0907/article/details/45601705)

编译arm平台的程序使用编译器arm-linux-gcc交叉编译

**Comment by HsingPeng** [comment]
@taocr 若需要测试arm构架，可以使用SDK里的google官方虚拟机。

**Comment by HsingPeng** [comment]
# 工作报告

[20160313_陶琛嵘_本周工作报告-交叉编译.md](https://github.com/openthos/printer-analysis/blob/master/report%2F20160313_%E9%99%B6%E7%90%9B%E5%B5%98_%E6%9C%AC%E5%91%A8%E5%B7%A5%E4%BD%9C%E6%8A%A5%E5%91%8A-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91.md)

[20160326_陶琛嵘_本周工作报告-ghostscript及foo2zjs静态编译移植及测试.md](https://github.com/openthos/printer-analysis/blob/master/report%2F20160326_%E9%99%B6%E7%90%9B%E5%B5%98_%E6%9C%AC%E5%91%A8%E5%B7%A5%E4%BD%9C%E6%8A%A5%E5%91%8A-ghostscript%E5%8F%8Afoo2zjs%E9%9D%99%E6%80%81%E7%BC%96%E8%AF%91%E7%A7%BB%E6%A4%8D%E5%8F%8A%E6%B5%8B%E8%AF%95.md)

# 文档

[交叉编译ghostscript及foo2zjs至android报告.md](https://github.com/openthos/printer-analysis/blob/master/%E7%A7%BB%E6%A4%8D%2F%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91ghostscript%E5%8F%8Afoo2zjs%E8%87%B3android%E6%8A%A5%E5%91%8A.md)

**Comment by HsingPeng** [comment]
@taocr 你编译时都没有`--host`参数，请确认你的开发环境的系统位数，和android_x86的位数，是32位还是64位。

**Comment by taocr** [comment]
@HsingPeng 开发环境是64位Linux系统，具体实验环境是64位android_x86系统。目前已经在[https://github.com/openthos/printer-analysis/blob/master/%E7%A7%BB%E6%A4%8D/%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91ghostscript%E5%8F%8Afoo2zjs%E8%87%B3android%E6%8A%A5%E5%91%8A.md](交叉编译ghostscript及foo2zjs至android报告.md)中添加了编译32位android_x86中使用的ghostscript及foo2zjs的具体参数

**Comment by taocr** [comment]
@HsingPeng 开发环境为64位Linux操作系统，实验所用的android_x86为64位。目前已在[交叉编译ghostscript及foo2zjs至android报告.md](https://github.com/openthos/printer-analysis/blob/master/%E7%A7%BB%E6%A4%8D/%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91ghostscript%E5%8F%8Afoo2zjs%E8%87%B3android%E6%8A%A5%E5%91%8A.md)中添加了编译32位android_x86所使用的ghostscript及foo2zjs的具体方法。
